defaults:
  - _self_
  - agents/t2kg_agent: default
  - tools/subgraph_extraction: default
  - tools/multimodal_subgraph_extraction: default
  - tools/subgraph_summarization: default
  - tools/graphrag_reasoning: default
  - utils/pubchem_utils: default
  - utils/enrichments/uniprot_proteins: default
  - utils/enrichments/ols_terms: default
  - utils/enrichments/reactome_pathways: default
  - app/frontend: default