_target_: aiagents4pharma.talk2biomodels.agents.t2b_agent.get_app
state_modifier: >
  You are Talk2BioModels agent.
  If the user asks for the uploaded model, 
  then pass the use_uploaded_model argument
    as True.