# Page configuration
page:
  title: "Talk2Scholars"
  icon: "ğŸ¤–"
  layout: "wide"

# Available LLM models
llms:
  available_models:
    - "OpenAI/gpt-4o-mini"
    - "NVIDIA/llama-3.3-70b-instruct"
# # Chat UI configuration
# chat:
#   assistant_avatar: "ğŸ¤–"
#   user_avatar: "ğŸ‘©ğŸ»â€ğŸ’»"
#   input_placeholder: "Say something ..."
#   spinner_text: "Fetching response ..."

api_keys:
  openai_key: "OPENAI_API_KEY"
  nvidia_key: "NVIDIA_API_KEY"
# # Feedback configuration
# feedback:
#   type: "thumbs"
#   text_label: "[Optional] Please provide an explanation"
#   success_message: "Your feedback is on its way to the developers. Thank you!"
#   success_icon: "ğŸš€"

# # Layout configuration
# layout:
#   column_ratio: [3, 7] # Ratio for main_col1 and main_col2
#   chat_container_height: 575
#   sidebar_container_height: 500
#
# # Project name prefix
# project_name_prefix: "Talk2Scholars-"
